---

include:
  - component: $CI_SERVER_FQDN/components/Pipelines/k8s-applicaton-dev-prod@v0.7.0
    inputs:
      image_name: elody-docs
      harbor_project_prefix: elody-dams

      values_repository: rnd/inuits/dams/elody-docs-helm-values
      values_file: elody.yaml
      values_key: .docs.image.tag

      build_secrets:
        - id=NPM_CONFIG_REGISTRY,env=NPM_CONFIG_REGISTRY
        - id=NPM_CONFIG__AUTH_TOKEN,env=NPM_CONFIG__AUTH_TOKEN
