site_name: Inuits DAMS Docs
nav:
  - CSV Export: csv-export.md
  - CSV Import: csv-import.md
  - OCR Service: ocr-service.md
  - Advanced Filtering: advanced-filtering.md
  - Input Fields: edit-fields.md
  - Advanced Filtering (deprecated version): advanced-filtering-deprecated-version.md
theme: readthedocs
